CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE movies (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) UNIQUE NOT NULL,
  year VARCHAR(255) NOT NULL,
  poster VARCHAR(255) NOT NULL,
  userId INT NOT NULL,

  FOREIGN KEY(userId) REFERENCES users(id)
);